### ISSUE TITLE
Script to automatically release new versions to Web store

### ISSUE THREAD

**Issue by Arthyon** [Arthyon/Unit4Enhancements#1]
link to api:
https://developer.chrome.com/webstore/using_webstore_api

**Comment by heinzmuller** [comment]
https://www.npmjs.com/package/chrome-webstore-upload - A node alternative

**Comment by Arthyon** [comment]
Ended up using this one: https://www.npmjs.com/package/webstore-upload

to run gulp a credentials.json-file is required:
`
{
    "clientId": "XXXXXXXXXXXXX",
    "clientSecret": "XXXXXXXXXXX",
    "refreshToken": "XXXXXXXXXXXXXXX"
}
`


To generate a new refresh token if it expires:
https://www.npmjs.com/package/webstore-upload
