### ISSUE TITLE
Automatically dismiss save confirmation on timesheets

### ISSUE THREAD

**Issue by kentrh** [Arthyon/Unit4Enhancements#11]
Automatically dismiss after a couple of seconds or remove altogether.

**Comment by Arthyon** [comment]
Fixed in PR #10

**Comment by Arthyon** [comment]
Oops, didn't read the title correctly. This was not fixed in #10

**Comment by asbjornh** [comment]
Maybe add different design (like a green stripe at the top) and hide the overlay that prevents page interaction
