### ISSUE TITLE
options-files missing from bundle

### ISSUE THREAD

**Issue by asbjornh** [Arthyon/Unit4Enhancements#15]
Occasionally, options.html and options.js are omitted when publishing extension

**Comment by Arthyon** [comment]
@asbjornh  Fixed in f2db502?

**Comment by asbjornh** [comment]
@Arthyon Hopefully but not necessarily. I can't reproduce the issue anymore

**Comment by Arthyon** [comment]
Cannot reproduce anymore. Closing issue
