### ISSUE TITLE
Add Custom Extension Icon

### ISSUE THREAD

**Issue by Arthyon** [Arthyon/Unit4Enhancements#2]

**Comment by heibjornendre** [comment]
https://developer.chrome.com/extensions/manifest/icons

![icon16](https://cloud.githubusercontent.com/assets/23025558/26315637/0a94965e-3f12-11e7-8069-8ff87fa66403.png)
![icon32](https://cloud.githubusercontent.com/assets/23025558/26315635/08fbbd9a-3f12-11e7-9afc-06f3c91718d3.png)
![icon48](https://cloud.githubusercontent.com/assets/23025558/26315632/06934960-3f12-11e7-850e-ffb4e50187c3.png)
![icon128](https://cloud.githubusercontent.com/assets/23025558/26315631/068dc22e-3f12-11e7-9b94-dde4fdfcfe6b.png)
