### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Xodaru** [Arthyon/Unit4Enhancements#22]
Hi,
I am wondering what is the license for this project? I am interested in forking it, making it more generic (not limited to Creuna installs) and adding some functionality.

My limited testing within my own organisation has been promising.

**Comment by asbjornh** [comment]
Hey!

Thanks for your interest :) I'll ask around and see if we can change it to an MIT license instead. I don't see why we would need this one copyrighted

**Comment by asbjornh** [comment]
Lol, ok, so the license file seems to actually be an MIT license, while the package.json `license` field specifies ISC. I'll update the one in package.json. If I understand MIT correctly you can go nuts as long as you include the original license file? I'm not a lawyer...

**Comment by asbjornh** [comment]
I've updated it so that both package.json and the license file specify MIT :)

I don't understand the copyright stuff but apparently that's how MIT licenses work.
